BEGIN;

-- EF Core for Npgsql uses quoted identifiers by default, so keep PascalCase names.
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" VARCHAR(255) NOT NULL,
    "PasswordHash" TEXT NOT NULL,
    "FirstName" TEXT NOT NULL,
    "LastName" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");

CREATE TABLE IF NOT EXISTS "Products" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
    "Description" TEXT NOT NULL DEFAULT '',
    "Price" NUMERIC(18,2) NOT NULL,
    "Sku" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "CK_Products_Price_NonNegative" CHECK ("Price" >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Sku" ON "Products" ("Sku");

CREATE TABLE IF NOT EXISTS "Inventories" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductId" INTEGER NOT NULL,
    "QuantityOnHand" INTEGER NOT NULL DEFAULT 0,
    "ReorderLevel" INTEGER NOT NULL DEFAULT 10,
    "ReorderQuantity" INTEGER NOT NULL DEFAULT 50,
    "LastUpdated" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "UX_Inventories_ProductId" UNIQUE ("ProductId"),
    CONSTRAINT "FK_Inventories_Products_ProductId"
        FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "CK_Inventories_NonNegative" CHECK (
        "QuantityOnHand" >= 0 AND "ReorderLevel" >= 0 AND "ReorderQuantity" >= 0
    )
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "Status" INTEGER NOT NULL DEFAULT 0,
    "TotalAmount" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "OrderDate" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ShippedDate" TIMESTAMPTZ NULL,
    "DeliveredDate" TIMESTAMPTZ NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Orders_Users_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "CK_Orders_Status" CHECK ("Status" BETWEEN 0 AND 5),
    CONSTRAINT "CK_Orders_TotalAmount_NonNegative" CHECK ("TotalAmount" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_Orders_UserId" ON "Orders" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Orders_OrderDate" ON "Orders" ("OrderDate" DESC);

CREATE TABLE IF NOT EXISTS "OrderItems" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" INTEGER NOT NULL,
    "ProductId" INTEGER NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "UnitPrice" NUMERIC(18,2) NOT NULL,
    CONSTRAINT "FK_OrderItems_Orders_OrderId"
        FOREIGN KEY ("OrderId")
        REFERENCES "Orders" ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_Products_ProductId"
        FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id")
        ON DELETE RESTRICT,
    CONSTRAINT "CK_OrderItems_Quantity_Positive" CHECK ("Quantity" > 0),
    CONSTRAINT "CK_OrderItems_UnitPrice_NonNegative" CHECK ("UnitPrice" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
CREATE INDEX IF NOT EXISTS "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");

COMMIT;
